### ISSUE TITLE
Singleplayer topic chooser add

### ISSUE THREAD

**Issue by LetsplesureONE** [ELdER1cH/HangingMan#1]

**Comment by LetsplesureONE** [comment]
@ELdER1cH Questions
- [x] more than only one language?
- [ ] posibility to add own ones by providing location?
- [x] choose the Topic, the words are from?
- [ ] where are we getting the lists? Creating them ourselfs?

**Comment by ELdER1cH** [comment]
The Word list are created by us.
The feature to add your own words, will be added soon.
